# Generated by Django 5.2.14 on 2026-05-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("date_added", models.DateField(blank=True, null=True)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Tech", "Tech"),
                            ("Finance", "Finance"),
                            ("Healthcare", "Healthcare"),
                            ("Construction", "Construction"),
                            ("Education", "Education"),
                            ("Energy", "Energy"),
                            ("Consulting", "Consulting"),
                            ("Hospitality", "Hospitality"),
                            ("Telecommunications", "Telecommunications"),
                            ("Media", "Media"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Private", "Private"),
                            ("Semi-Government", "Semi-Government"),
                            ("Government", "Government"),
                            ("NGO", "NGO"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "linkedin_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "handshake_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("signed_mou", models.BooleanField(default=False)),
                ("is_favorite", models.BooleanField(default=False)),
                ("is_blacklisted", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("job_title", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_blacklisted", models.BooleanField(default=False)),
                ("available_for_presentations", models.BooleanField(default=False)),
                ("is_alumni", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="employers.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "ordering": ["company__name", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Workshop", "Workshop"),
                            ("Information Session", "Information Session"),
                            ("Career Fair", "Career Fair"),
                            ("Networking Event", "Networking Event"),
                            ("Panel", "Panel"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "companies",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="employers.company"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("Email", "Email"),
                            ("Phone Call", "Phone Call"),
                            ("Meeting", "Meeting"),
                            ("Site Visit", "Site Visit"),
                            ("Workshop", "Workshop"),
                            ("Career Fair", "Career Fair"),
                            ("LinkedIn", "LinkedIn"),
                            ("Handshake", "Handshake"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("summary", models.TextField()),
                ("follow_up_needed", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="employers.company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to="employers.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interaction",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InternshipRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "semester",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Spring", "Spring"),
                            ("Summer", "Summer"),
                            ("Fall", "Fall"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("student_count", models.PositiveIntegerField(default=0)),
                ("program", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internship_records",
                        to="employers.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internship Record",
                "ordering": ["-year", "company__name"],
                "unique_together": {("company", "year", "semester", "program")},
            },
        ),
    ]
